# Generated by Django 6.0.2 on 2026-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(default='İsimsiz', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
