# Generated by Django 6.0.2 on 2026-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='static_url',
            field=models.CharField(default='img/default.png', max_length=200),
        ),
    ]
